### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by uoziod** [binhex/arch-delugevpn#111]
Suddenly stopped working. Logs excerpt:
![image](https://user-images.githubusercontent.com/169145/57401123-47516480-71d5-11e9-98ae-ea873498932c.png)

**Comment by iensenfirippu** [comment]
I've been having a similar issue. But it started when I updated to: **Docker version 18.09.5-ce, build e8ff056dbc**, about 2 weeks ago.

But I had to update my entire system (Arch Linux), so it could be Docker or it could be some library or something.

Here is my log:

```
Fri May 17 23:41:03 2019 us=923902 Incoming Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Fri May 17 23:41:03 2019 us=923920 WARNING: cipher with small block size in use, reducing reneg-bytes to 64MB to mitigate SWEET32 attacks.

2019-05-17 23:41:03,924 DEBG 'start-script' stdout output:
Fri May 17 23:41:03 2019 us=924144 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02

2019-05-17 23:41:03,926 DEBG 'start-script' stdout output:
Fri May 17 23:41:03 2019 us=926628 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
Fri May 17 23:41:03 2019 us=926664 Exiting due to fatal error
```

I'm pretty sure this has something to do with DNS or network accessibility. Since I can ping all the IP's in my /etc/resolv.conf ...But If try to ping Google.com I get:

```
[root@b74299f781f3 /]# ping -c 1 google.com
ping: google.com: Temporary failure in name resolution

[root@b74299f781f3 /]# ping -c 1 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=55 time=23.6 ms
```

_(Note: this seems to only affect the arch-delugevpn docker)_

**Comment by binhex** [comment]
its not dns related, the reason you cant resolve anything is because name resolution is blocked to prevent ip leakage (vpn endpoint once resolved is written to hosts file). 

so your issue is this:-

```ERROR: Cannot open TUN/TAP dev /dev/net/tun:```

until you resolve this on your host (not container) then you will not be able to establish a vpn tunnel, few links from some quick googling:-

https://bbs.archlinux.org/viewtopic.php?id=156154
https://bbs.archlinux.org/viewtopic.php?id=194971
https://bbs.archlinux.org/viewtopic.php?id=158196

**Comment by beaceves** [comment]
It suddenly stopped working for me too... It was downloading fine then the downloads slowed and eventually stopped. I see this at the bottom for the download info "Tracker Status:
Error: Cannot assign requested address" I tried rebuilding it and I still get the same problem.
Using a QNAP TS 451+ with container station
