### ISSUE TITLE
Default data directories should be in /data

### ISSUE THREAD

**Issue by ricka** [binhex/arch-delugevpn#158]
The last update to the included conf file changed the default locations of downloaded files out of /data. Data should default to being stored there as described by the Docker usage. I created #154 to address this.

**Comment by vidia** [comment]
In the meantime you can manually set preferences to switch the folder. It isnt the most elegant solution of course because I doubt it will persist after a reboot. But at least its a workaround.

![image](https://user-images.githubusercontent.com/4712072/78985705-4b20f180-7ade-11ea-9408-2ce440aa1a48.png)
