### ISSUE TITLE
DMCA with container and PIA

### ISSUE THREAD

**Issue by LrrrAc** [binhex/arch-delugevpn#162]
I'm not blaming you or this container for it, I was just wondering if you would have any idea how I would still get a DMCA with this container running with PIA. You say that iptables prevent access unless though the VPN, so I'm trying to find any and all holes to plug. Thanks!

**Comment by fryfrog** [comment]
Have you tried one of those torrent leaking test sites? Fire one of them up and see how it does. Kill the VPN connection, see if it leaks.

**Comment by binhex** [comment]
can you do the following procedure:-
https://github.com/binhex/documentation/blob/master/docker/faq/help.md

**Comment by LrrrAc** [comment]
[supervisord1.log](https://github.com/binhex/arch-delugevpn/files/4192819/supervisord1.log)
[supervisord2.log](https://github.com/binhex/arch-delugevpn/files/4192820/supervisord2.log)
I've attached two log files, 1 is when it gives stdout errors which is new, and 2 is when it functions correctly. Also yes I have done several of the ip leak tests and they never show my actual ip when the vpn is running, but it obvious got through somehow. The right ip was on the letter. Thanks for the quick responses!

**Comment by binhex** [comment]
so i see no issues with your config, this image is water tight in respect to iptables, ive done extensive checking at packet level to make sure there is no leakage under any circumstance, e.g. vpn down, vpn up, vpn coming up and vpn going down, and i have yet to see any evidence to the contrary, the ONLY exception to this is point 5. shown below.

please verify ALL of the following statements are true:-

1. no other torrent clients on ANY devices are running, including smart phones, tablets, etc
2. you do not use a proxy or anything else to try and 'secure' deluge
3. the dmca notice was definitely for a linux iso that you had/were downloading
4. you at no point set vpn_enabled to no
5. you did not use the 'docker pause' command - please check any updater (such as watchtower) or backup utility also did not perform this.

conjecture follows, do not take this as gospel!:- 

so i see you used pia endpoint 'ca-toronto.privateinternetaccess.com', so something odd happened with this endpoint, as well as ca-montreal.privateinternetaccess.com, i noticed yesterday that all of a sudden these two endpoints stopped being able to talk to the pia api in order to get a incoming port. both of these endpoints support port forwarding, and today both are operational again.

now im not saying for sure that the issue was a vpn provider leak, as that is a major issue (and a worrying one, i use pia myself!), however its suspicious that you received a notice on the day that pia had issues, perhaps even misconfiguration of these two endpoints caused a leak, leading to a frantic shutdown of both of these endpoints by the provider, this is purely a theory!.

i have actually seen something similar happen once before a year or so ago, two people posted at the same time on the support forum saying they both had got notices that minute (automated dmca via email), both connected to pia and both connected to the same endpoint - the endpoint was then un-connectable for a period of time!, pia pulling the plug?, perhaps?.

obviously if this IS the case (impossible to prove as the leak is at the vpn end) then there is little to do other than switch vpn provider.

**Comment by binhex** [comment]
OK done some digging and found the links to the forum posts, one was a PM so i cant show that, but here are the two posts, one is mine just mentioning that the other guy with the notice also was connected to ca-toronto.

https://forums.unraid.net/topic/44109-support-binhex-delugevpn/?do=findComment&comment=705671

https://forums.unraid.net/topic/44109-support-binhex-delugevpn/?do=findComment&comment=705694

one thing to note is, guess what endpoint they were both connected to?, yep you guessed it, PIA ca-toronto, a coincidence?, hmmm.

**Comment by LrrrAc** [comment]
Holy shit man. You blew the cover of the whole thing. Thats a ridiculous amount of info. THANKS!! 1-4 are definitely not a thing for me, I only use the one box, ive burned proxies from my life long ago, I did grab said iso 3 days prior to the date stated so It would have been still in my client, and Ive never changed my docker-compose file for it. Its creepy that youre finding exactly identical issues from other people. I tried to look up stuff, but I guess I was too vague to find the other occurances. WEIRD. Thanks for the info, love your container! Looks like I might go back to using it instead of the 'Freaking out seedbox' I switched too lol.

**Comment by LrrrAc** [comment]
I also thought it was odd that this happened soon after PIA was being acquired by their new parent company. I already cancelled my subscription with them before this even happened because of the acquisition.

**Comment by binhex** [comment]
> 1-4 are definitely not a thing for me,

can i also ask, is point 5. a possibility?, as this could lead to possible ip leakage.

**Comment by LrrrAc** [comment]
Oh no I dont know if Ive ever used pause. I have scripts that use docker-compose stop and start. But thats about it.

**Comment by binhex** [comment]
ok i will leave this issue open for a few days, @fryfrog any thoughts on any of the above?, am i crazy or just paranoid :-).

@LrrrAc for now, just incase i would recommend steering clear of all Canadian endpoints, there are plenty of others to choose from, so go with another that supports port forwarding.

**Comment by fryfrog** [comment]
You're *way* beyond my skills and knowledge, but that is some amazing digging and I can't find any reasonable fault w/ it. But I can't imagine PIA will ever confirm or provide proof against either, so how to ever really know?

Do the auto updating apps like watchtower and oroumbobourorurs actually *pause* the containers? My admittedly shallow understanding is that they just pull and restart.

**Comment by fryfrog** [comment]
I don't know how accurate this is, but [search for pause](https://github.com/containrrr/watchtower/search?q=pause&unscoped_q=pause) finds nothing. :/

**Comment by fryfrog** [comment]
[Same for ouroboros](https://github.com/pyouroboros/ouroboros/search?q=pause&unscoped_q=pause)

**Comment by binhex** [comment]
> But I can't imagine PIA will ever confirm or provide proof against either, so how to ever really know?

this is the kicker, even if it were true pia would NEVER confess to this as it would instantly zero any credibility they have, so i guess all we have to go on is what has been seen and the odds of it just being a coincidence (or not).

> do the auto updating apps like watchtower and oroumbobourorurs actually _pause_ the containers?

a good question, i honestly dont know, but looking at your quick code searches it appears that is a negative, so those apps are clear of using the 'docker pause' command, as long as they dont issue that specific command then its fine.

**Comment by LrrrAc** [comment]
It's sure making me worry about vpns in general. Time for weeks of research.

**Comment by binhex** [comment]
An interesting twist in the tale PIA turned off all port forwarding and have recently just turned it back on but have not done so for any of the Canadian servers I wonder why that might be

**Comment by binhex** [comment]
Taken from a post on Reddit so it could be bs, but:-

FYI, Talked to a support tech via chat and got the 411:

"On the evening of March 30th, our DevOps team became aware of an issue that required us to temporarily disable port-forwarding. Once the issues, that resulted in this change were addressed, port-forwarding was enabled immediately on all but our Canadian servers. We don't currently have a timetable for the restoration of port-forwarding capabilities on our servers in Canada."
