### ISSUE TITLE
Iptables block connections if delugevpn run with docker-compose

### ISSUE THREAD

**Issue by spirkaa** [binhex/arch-delugevpn#21]
Server config: proxmox 4.4 -> centos 7 lxc -> docker 1.13.1

I run delugevpn with other NAS-related containers (sonarr, couchpotato, plex) with docker-compose. Compose create their own docker network - [https://docs.docker.com/compose/networking/](https://docs.docker.com/compose/networking/)

Your iptables rules accept connections only in bridge network (172.17.0.0/16). 
If you try to run container with docker-compose, docker create network (172.18.0.0/16 in my case) and container services will be inaccessible from this network - other containers in Compose app can't communicate with delugevpn. Though i can connect to webui (8112) and daemon (58846) from LAN_NETWORK (192.168.10.0/24), but not to privoxy (8118)

I replace 172.17.0.0/16 to 172.16.0.0/12 in [iptable.sh](https://github.com/binhex/arch-delugevpn/blob/master/apps/root/iptable.sh) and this seems to work for me.

**Comment by fryfrog** [comment]
A good solution might be making it an environment variable that could be passed in?

**Comment by jshridha** [comment]
I think reading the /etc/hosts file and setting the value based on that
specified subnet should work most universally.

**Comment by fryfrog** [comment]
Does Docker put the local network in there?

**Comment by fryfrog** [comment]
Neat, it sure does...
```
172.17.0.2      f59728a82f5b
```

**Comment by binhex** [comment]
@jshridha this is exactly the sort of thing i had in mind, however that might not tell you the network mask, so possibly use of ifconfig might be better, leave it with me.

**Comment by binhex** [comment]
@jshridha i believe this is now fixed in the latest image, please pull it down and give it a whirl. please report back your results.

**Comment by joeknock90** [comment]
Hey @binhex. 

I'm still getting this issue. It is also entirely possible I am doing something wrong.

I add your repos as a collection on FreeNAS 10 and sonarr running on the same docker host cannot access the container via it's NAT address (i.e. [NASIP]:8112) but fortunately as a workaround I can use the docker container IP. 

I'm going to try building it directly on the docker host without using the GUI (because frankly I'm not entirely sure what kind of black magic the devs at iXsystems are using to make that GUI work).

I'll report back after I do that. Just wanted to let you know.

**Comment by dakipro** [comment]
Hi @binhex , after a lot of googling I think I have this issue.
I am using Ansible to deploy delugeVpn, and it works fine, I can connect to it from browser and local network to use server:8118 as proxy from f.eks. firefox.

I then try to connect lidarr trough same proxy by adding both delugeVpn and lidarr to the same docker network, f.eks. "openvpn"

From lidarr I can ping towards delugevpn, but I never get ping back
[root@f054d7da8355 /]# ping delugevpn
PING delugevpn (172.19.0.3) 56(84) bytes of data.
and then nothing back.

Same with "wget delugevpn" responce is "Resolving delugevpn (delugevpn)... 172.19.0.3"

When I log into delugevpn container and I try to ping lidarr i get:
[root@438e01199773 /]# ping lidarr
ping: lidarr: No address associated with hostname

both have default network_mode docker creates

However, since I am not that familiar with docker, I might be doing something very wrong. 
(I tried to use server_ip:8118 from lidarr, but get proxy exceptions)

If this is a wrong approach, how would I connect containers, so that other containers can use privoxy as their proxy? (rather with "restart-proff" settings, meaning it would work on restart etc )

Thanks for the awesome work on the container btw :)

**Comment by dakipro** [comment]
Hi, please disregard my last comment, I managed now to connect to privoxy, it was different setting syntax for other containers, it works as I need it now via bridged network.

Thanks again for the container, works awesome!
