### ISSUE TITLE
Slow connection with PIA inside of container

### ISSUE THREAD

**Issue by theotherp** [binhex/arch-delugevpn#217]
I'm using your container with PIA and their next-gen servers. I'm getting slow torrent speeds (and almost no upload) so I decided to test the connection speed and compare it. I ran `https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py` from inside the container with VPN enabled and got 40Mbit/s. With VPN disabled I got 200Mbit/s. 

Connecting to the same PIA server using their client on my host machine the speed test gives me about 180Mbit/s (without VPN I get 700Mbit/s).

Any ideas why this may happen? Thanks.

Btw, do I need to remove anything except username and password from [log_sanitized.log](https://github.com/binhex/arch-delugevpn/files/5424598/log_sanitized.log)?

**Comment by binhex** [comment]
> I'm getting slow torrent speeds (and almost no upload) so I decided to test the connection speed and compare it. I ran `https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py` from inside the container with VPN enabled and got 40Mbit/s. With VPN disabled I got 200Mbit/s.

i see your host is running windows, i would suspect the issue is with docker running on windows as opposed to the container itself. sadly my dl/ul rates aren't too high for my connection, so i can only max out at 32Mb/s, but it does max my line out.

i have heard of people running my image who have achieved a lot higher speeds than what you are reporting so that does give me confidence there are no inherent issues with the image.

> Btw, do I need to remove anything except username and password from [log_sanitized.log](https://github.com/binhex/arch-delugevpn/files/5424598/log_sanitized.log)?

thats all that is really required, but some people are more paranoid and remove remote ip addresses, dns etc, but its really not necessary imho.

**Comment by theotherp** [comment]
I'll try and get a dual boot running and see if it's faster with linux as host OS.

**Comment by theotherp** [comment]
For the record: PIA client 1.5 supports routing only certain applications through the VPN. It's not as tight as using a container but it does deliver the expected speeds.

**Comment by semioniy** [comment]
You might wanna switch from openvpn to wireguard in your container settings, it got me from +-400KiB/s to over 10MB/s, tested on multiple servers.
