### ISSUE TITLE
PIA Wireguard not working at all

### ISSUE THREAD

**Issue by HNGamingUK** [binhex/arch-delugevpn#226]
Hello,

I was testing to see if I could use wireguard to improve performance/speed etc. I have strict port forwarding on but while it is starting and attempting to get a port it keeps erroring with the following: 

`Unable to successfully download PIA json payload from URL`

It retries multiple times and then fails. 

With port forwarding off I get the following: 
```
2020-11-23 09:18:52,771 DEBG 'start-script' stderr output:
parse error: Invalid numeric literal at line 4, column 0

2020-11-23 09:19:24,718 DEBG 'start-script' stdout output:
[warn] Unable to successfully download PIA json to generate token from URL 'https://212.102.52.134/authv3/generateToken'
[info] Retrying in 10 secs...
```

Because of this it means that either way it won't connect and the webui doesn't load.

**Comment by HNGamingUK** [comment]
As a further to this, I had the LAN_NETWORK env set to `10.0.0.0/8` because I have multiple subnets setup and may want to test access from any one of those subnets. 

I have changed it to `10.0.2.0/24` as a test and it actually connects now with strict port forwarding enabled...

**Comment by binhex** [comment]
you can specify multiple subnets, seperate with comma's, e.g.:-

`10.0.2.0/24,10.0.3.0/24`

**Comment by HNGamingUK** [comment]
Ah okay, I was unsure if that would work. 

Thanks for the quick response. I will close this off since it is actually working now.

**Comment by ruok5** [comment]
> 
> I have changed it to `10.0.2.0/24` as a test and it actually connects now with strict port forwarding enabled...
>
This solved my issue, too. I thought to leave a comment for others who retrace my steps, because my environment variables were taken from a previous deployment of this image, about two years ago. I was using openvpn then, which may have been part of why `10.0.0.0/8` still worked. The point is, I wasted hours troubleshooting choice of endpoints and suspecting PIA network problems, when this was something I should have revisited sooner. Thanks for posting your results, @HNGamingUK.
