### ISSUE TITLE
OpenVPN/AirVPN broken - options error

### ISSUE THREAD

**Issue by fongd** [binhex/arch-delugevpn#230]
The latest build released this morning is producing an error that I haven't experienced with previous releases:

<pre>
2020-11-28 10:03:36,969 DEBG 'start-script' stdout output:
[info] Starting OpenVPN (non daemonised)...

2020-11-28 10:03:36,975 DEBG 'start-script' stdout output:
2020-11-28 10:03:36 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.

2020-11-28 10:03:36,975 DEBG 'start-script' stdout output:
Options error: --explicit-exit-notify can only be used with --proto udp
Use --help for more information.
</pre>

I'm using an AirVPN config file with the following options in the .ovpn file provided by their online configurator:

<pre>
client
dev tun
remote ca.vpn.airdns.org 443
resolv-retry infinite
nobind
persist-key
auth-nocache
route-delay 5
verb 3
explicit-exit-notify 5
push-peer-info
setenv UV_IPV6 yes
remote-cert-tls server
cipher AES-256-CBC
comp-lzo no
proto udp
key-direction 1
</pre>

If I comment out `explicit-exit-notify`, the container successfully starts up but I don't know what the consequences of this are.

**Comment by barth-lornsen** [comment]
Hi. I'm experiencing the same issue for the last update of the container. If I comment "explicit-exit-notify", I'm able to access deluge WebUI but I get an error when I add a torrent file. And no torrent seems able to contact trackers.

**Comment by Melantrix** [comment]
Same problem and solution, the torrents do download however.

**Comment by kriegalex** [comment]
> –explicit-exit-notify [n]
In UDP client mode or point-to-point mode, send server/peer an exit notification if tunnel is restarted or OpenVPN process is exited. In client mode, on exit/restart, this option will tell the server to immediately close its client instance object rather than waiting for a timeout. The n parameter (default=1) controls the maximum number of attempts that the client will try to resend the exit notification message.In UDP server mode, send RESTART control channel command to connected clients. The n parameter (default=1) controls client behavior. With n = 1 client will attempt to reconnect to the same server, with n = 2 client will advance to the next server.
OpenVPN will not send any exit notifications unless this option is enabled.

Seems to me like this command can be temporarily disabled, if you don't reconnect too often to the server. Negative impact may be a longer time to reconnect to the same server, waiting for the timeout ?

**Comment by Johnorizabal** [comment]
I have the same issue. Started a thread on reddit to find some assistance and /u/canuck_sysadm and /u/smikwily told to roll back the repository.

**Comment by binhex** [comment]
i think i have spotted the issue with the protocol problems, please can somebody try using the 'test' tagged image just built, let me know if it works, if so i will push to latest.

**Comment by Bodgers** [comment]
> 
> 
> i think i have spotted the issue with the protocol problems, please can somebody try using the 'test' tagged image just built, let me know if it works, if so i will push to latest.

I had the problem with `latest`.  `2.0.4.dev38_g23a48dd01-2-15` works and I can confirm `test` works too. Using ExpressVPN.

**Comment by binhex** [comment]
fixed in latest, please pull down (just built).

**Comment by fongd** [comment]
Confirmed fixed for me, too. Thanks @binhex!

**Comment by barth-lornsen** [comment]
Thanks a lot binhex 👍
