### ISSUE TITLE
.ovpn file required for PIA?

### ISSUE THREAD

**Issue by dismantl** [binhex/arch-delugevpn#33]
I have been using this docker image with PIA. When I recently updated the image, I'm getting an error about an .ovpn config file not being present. Is this now required for using PIA? Is there a way the config file could be auto-generated, or do we need to provide one? If we need to provide one, it would be good to add that to the documentation.

**Comment by binhex** [comment]
in a word, yes, i got burnt with ovpn changes from pia a while back and decide it is better to push the responsibility of having an up to date ovpn file back to the user, thus the removal.

documentation updates coming soon.

**Comment by rcdailey** [comment]
> soon

2 years later...

**Comment by binhex** [comment]
It's in the readme.md and had been for some time

**Comment by rcdailey** [comment]
It's in the Notes section, which is a little misleading, I expected it to be under the PIA section, or at least a note instructing users to read more about requirements at the bottom. No biggie, I figured it out the hard way after my last comment. Might be worth making this more obvious for the future, but not a super serious issue.

**Comment by Thunderoux** [comment]
Restarted my container today and now I get error about "No OpenVPN config file located in /config/openvpn/ .. please donwload from your VPN provider and then restart this contaienr, exiting...

No changes have been made to the file since last restart (test on redownload new ovpn file didnt work). It is any new update that causes this?
