### ISSUE TITLE
OpenVPN broken in 2.1.1-4-01 

### ISSUE THREAD

**Issue by tech1ndex** [binhex/arch-delugevpn#362]
### Environment

- Docker Version:
20.10.18 running on Unraid Version: 6.11.1
- binhex-delugevpn container

### Issue
After updating the binhex-deulgevpn container to 2.1.1-4-01  the following message is repeated in the container logs:

```
Bad compression stub (swap) decompression header byte: 250
```

As a result , the container has no network connectivity at all.

### Mitigation
Downgrading back to 2.1.1-3-07 resolves the issue

**Comment by ChrisBaker97** [comment]
Same issue, same workaround on Synology DSM 6.2.4-25556 Update 7.

**Comment by binhex** [comment]
LMGTFY https://community.openvpn.net/openvpn/ticket/861

**Comment by ChrisBaker97** [comment]
Thanks. Interesting that the linked post is six years old, yet this issue just began appearing in `arch-delugevpn` recently.

For others coming across this, my `.ovpn` file didn't have a `comp-lzo` entry, but did have `compress`. In order to get this working with the latest release of `arch-delugevpn` I had to both remove `compress` and add `comp-lzo yes`.
