### ISSUE TITLE
DelugeVPN won't start after april 1st update.

### ISSUE THREAD

**Issue by dnmaia** [binhex/arch-delugevpn#395]
I run the Docker delugeVPN on synology and after the today's update it won't start. It stops the starting process on the beginning.
![image](https://github.com/binhex/arch-delugevpn/assets/62720340/18ae977b-5a47-4772-8342-490ec6c23b48)

**Comment by dnmaia** [comment]
Anyone having this problem with the Docker?

**Comment by AmansRevenger** [comment]
Check your deluged.log in your /config folder.

For me it said 

`Unable to start deluged: [('SSL routines', '', 'ee key too small')]`

so I deleted the /config/ssl directory and restarted the container, and voila. 

Apparently some openSSL libs got updated or something? But it works now

**Comment by dnmaia** [comment]
Still the same for me. It got stuck on the screen above and don't move on.

**Comment by gabestover** [comment]
Same for me as well.  I went so far as to delete the whole /config folder and re-pulled the image, and it still sticks at:

[info] VPN_OPTIONS not defined (via -e VPN_OPTIONS)

like in the initial post

**Comment by dnmaia** [comment]
Just did the same thing. Delete all and downloaded again but stick there and not even create the files and folders on the config folder.

**Comment by dnmaia** [comment]
How the dock is wrong? It was working correctly, then watchtower updated the con anymore. I deleted the container and downloaded again the latest, setup everything again from scratch and the problem still there. I think there is something on the latest version that is causing that.

**Comment by dnmaia** [comment]
I deleted the entire config folder and it looks like it was something in that folder preventing the start. Can't say what file. Problem is , now i need to include all the torrent files again manually.

**Comment by dnmaia** [comment]
i will keep a backup of the working config folder in case of a new update messes with something.

**Comment by gabestover** [comment]
Is there any update on this?  even on a completely fresh pull of the docker image, I'm not getting anywhere - same log info as listed in this thread.

**Comment by dnmaia** [comment]
I deleted the complete content of the vonfig folder and deluge vpn started normally

**Comment by gabestover** [comment]
Thanks!  I tried that a couple times last week and it didn't do anything.  This time, thankfully, it did - all is well now!

**Comment by lediszep** [comment]
no fix on this? mine started doing this even though I removed everything

**Comment by StoverTech** [comment]
I realized what the problem was (for me, at least).  After removing everything and trying again, nothing worked still.  It turned out that my VPN provider had gotten rid of the specific server I was connecting to, and that was causing things to fail to start.  Once I replaced the VPN config with a good/working one, it fired right up as it should.

**Comment by gabestover** [comment]
I realized what the problem was (for me, at least). After removing everything and trying again, nothing worked still. It turned out that my VPN provider had gotten rid of the specific server I was connecting to, and that was causing things to fail to start. Once I replaced the VPN config with a good/working one, it fired right up as it should.

**Comment by lediszep** [comment]
Same for me, was the vpn config..
