### ISSUE TITLE
Question: What happens when the VPN disconnects

### ISSUE THREAD

**Issue by Zoidster** [binhex/arch-delugevpn#58]
Will it retry/block all traffic/use the unprotected connection?
Haven't seen it mentioned in the readme, maybe that could be a helpful addition :)

**Comment by binhex** [comment]
it will retry to connect to a randomly selected repote ip address (generated from dns lookup of named endpointat startup) and get an incoming port (if pia provider).

there is NO leakage of ip address at any time, this is ensured by employing ip tables, so its blocked always whether the connection is up, down or otherwise :-)
