### ISSUE TITLE
Traefik for Deluge

### ISSUE THREAD

**Issue by gurabli** [binhex/arch-delugevpn#80]
I have everything configured, and would like to run Deluge with Traefik, so that I could access Deluge with deluge.domain.com address. I added the required configuration but it doesn't work (it works for other containers).
Any idea how to make Traefik work with Deluge?

**Comment by binhex** [comment]
This is probably unlikely to work due to the very highly restrictive iptables rules in place, you would need to work out what rules to create/edit in order for this to work.

**Comment by gurabli** [comment]
Thank you! Then probably thiy6is one of the reasons it is not working in Plexguide too.

I don't know Traefik enough to know which ports need to be opened. Do you plan to check amd add an option to set the Traefik in iptables?

**Comment by binhex** [comment]
no, im afraid not, i got a lot going on and not enough time as per normal, feel free to fork and have a play though.

**Comment by gurabli** [comment]
Sure, same problem here (time). I will look into it and see if I can do it, once I find some time.
Thanks for the great work!

**Comment by JoooostB** [comment]
@gurabli Did you manage to figure this out?

**Comment by Gecko-with-a-hat** [comment]
Have you found a solution yet? @JoooostB 

Is there anything else besides the iptable rules that stops this from working? @binhex

I started the container with the vpn enabled and flushed all iptables with `sudo docker exec -it delugevpn iptables -F` and then changed the policies to "ACCEPT" with `sudo docker exec -it delugevpn iptables -P INPUT ACCEPT` (same for "OUTPUT" & "FORWARD"). Then I saved the config with `sudo docker exec -it delugevpn iptables-save` and I still was not able to connect to the webui with Traefik. I know that the traefik setup is working fine because I can use it without issue to connect to the webui when I turn off the vpn in my delugevpn docker compose. 

I am new to working with iptables so maybe I did something wrong. Not looking for you to fix my setup for me, but a guiding hand as to where I should be looking to get it working would be amazing. Love the software either way!

**Comment by JoooostB** [comment]
@Gecko-with-a-hat No I did not end up fixing it, I migrated to a [GlueTUN](https://github.com/qdm12/gluetun) sidecar set-up.

**Comment by Gecko-with-a-hat** [comment]
> @Gecko-with-a-hat No I did not end up fixing it, I migrated to a [GlueTUN](https://github.com/qdm12/gluetun) sidecar set-up.

Thanks for your reply!
I'll look into that. Was thinking of maybe using Nginx just for DelugeVPN and then rerouting from Traefik through Nginx. But it might be easier to go with your solution.
