### ISSUE TITLE
WebUI Times out

### ISSUE THREAD

**Issue by Edward70891** [binhex/arch-delugevpn#92]
I've installed the container with dockstarter on a remote ubuntu server I rent. I've configured as much as I can, but the webUI consistently times out on [external IP]:8112. Most of my other containers work fine on their respective ports, but deluge vpn does not seem to.
Within the logs, I see mentions of 0.0.0.0 as the deluge listening port (which doesn't seei'm runinm right) and a LAN_ADDRESS, which I let dockstarter use the system default for, because I'm not sure what else I should enter in that field. The logs are attached, with relevant IPs and my vpn credentials censored.
[delugelogs.txt](https://github.com/binhex/arch-delugevpn/files/2799363/delugelogs.txt)

**Comment by jadrian2006** [comment]
Have you tried connecting with the thin client from the desktop clients?

https://dev.deluge-torrent.org/wiki/UserGuide/ThinClient

I stopped using the built in web and started using a thin client from my Windows PC and it works var better.

**Comment by Edward70891** [comment]
> Have you tried connecting with the thin client from the desktop clients?
> 
> https://dev.deluge-torrent.org/wiki/UserGuide/ThinClient
> 
> I stopped using the built in web and started using a thin client from my Windows PC and it works var better.

Is there a way to set initial credentials outside of the webUI?

**Comment by jadrian2006** [comment]
Go to your config directory look for the file auth 

- if you cant find it, you can do the following
docker exec -it <docker name here> /bin/bash
example: docker exec -it delugevpn /bin/bash

cd /config
cat auth

then add your information

echo "username:password:10" >> auth

restart your docker image, then that login should work in your thin client.

**Comment by Edward70891** [comment]
This doesn't appear to work, and I think I need a webUI for radarr and sonarr to work correctly.

**Comment by snugglej** [comment]
I'm going to try this image and see how it goes. I know you need the web interface on 8112 to use sonarr and radarr.  

So if delige-webui is not installed it will never work. 

I'll respond with what I find tonight.

**Comment by snugglej** [comment]
So I ran into a similar issue, but maybe not the same. I have a network at my house that has multiple networks attached to it. So I wasn't able to attach to the web-ui and it timed out if I just specified one network. Since i have only rfc 1918 in here I went ahead and added all of them because the code allows for multiple LAN_NETWORKS as long as you comma separate them.

@Edward70891 You would need to add your public IP address to this LAN_NETWORKS list. So for example if you had 75.120.53.4. You would add 75.120.53.4/32 and then the webui would be routed over the standard eth0 interface instead of the the tunnel.

For me I had to just since i used a wide range of IPv4 addresses:
-e LAN_NETWORK=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12

**Comment by binhex** [comment]
due to very tight iptables (for obvious reasons) VPS are not supported, this docker image was designed around the idea that you always have a LAN, this is not the case for VPS, you are of course free to play but you may cause ip leakage if you mess with iptables.
